### PR TITLE
Update translation for `zh_CN`

### PR DESCRIPTION
**Pull request by initialdmg**
## Description

Add translation for Todos, and correct several improper translations.

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

### CODE REVIEW

**Comment by KaiVolland** [comment]
Thank you very much! I think you have to change your commit message to start with `feat(i18n):`. Afterwards we can merge this.

**Comment by initialdmg** [comment]
Sorry, it's been a while since last PR. Commit message has been updated and pushed according to the guide.  
I'm glad that we have contributing guide to follw on the commit message now.

**Pull request merged**
