### PR TITLE
Fix browser build dev setup

### PR DESCRIPTION
**Pull request by hwbllmnn**
## Description

This fixes the browser build dev setup.

## Pull request type

- [x] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [BSD 2-Clause License](https://github.com/geostyler/geostyler/blob/master/)
- [x] I have followed the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by KaiVolland** [comment]
Can you explain why the `MiniCssExtractPlugin` causes the problem and removing solves it?

**Comment by KaiVolland** [comment]
Maybe removing the `hmr` option is sufficent.

**Comment by hwbllmnn** [comment]
> Maybe removing the `hmr` option is sufficent.

Perhaps it is, I didn't really analyze the problem. I noticed the dev build was not working any more and then compared the build config with the production browser build file and noticed that the plugin is not present there (at least not in the `less` section). So I just made sure that both builds work the same (minus the optimizations for prod obviously).

**Comment by KaiVolland** [comment]
The docs of `MiniCssExtractPlugin` say that `hmr` is deprecated for webpack 4. Maybe give it a try. If it's not working we can remove it completly.

**Comment by hwbllmnn** [comment]
> The docs of `MiniCssExtractPlugin` say that `hmr` is deprecated for webpack 4. Maybe give it a try. If it's not working we can remove it completly.

Why do you want to keep the plugin in the dev build only? I'd prefer to have the dev build as close to the prod build as possible.

**Comment by hwbllmnn** [comment]
Also, removing the `hmr` option does not fix the problem. We get this error for all files:

```
ERROR in ./src/Component/Symbolizer/SLDRenderer/SLDRenderer.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ReferenceError: document is not defined
```

**Review by KaiVolland — APPROVED** [review]

**Pull request merged**
