### PR TITLE
Add locale zh-CN

### PR DESCRIPTION
**Pull request by initialdmg**
# Thank you 💞

Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.

## Some guidelines for the proposed change

Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.

Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.

Again: thank you for your contribution.

------------

## Description

This PR adds basic zh-CN locale support to components and editor. Improvement welcomed!

## Releated issues or pull requests

Please list issues or pull requests that the changes you propose are related to. It does not matter if they are still open and/or unmerged, any link is appreciated.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [BSD 2-Clause License](https://github.com/geostyler/geostyler/blob/master/)
- [x] I have followed the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jansule** [comment]
@initialdmg Thank you for your contribution.

I'm not very familiar with zh-CN, so could you please explain if there is a specific reason why the translations have different styles? 

I.e. some words are in zh-CN (e.g. 编辑器), others in EN (e.g. Version), others in both EN and zh-CN (e.g. 标称数Nominal), some have a `...` prefix (e.g. 选择……) and others have `...` suffix (e.g. ……被 k-Means 分类影响。).

**Comment by initialdmg** [comment]
It's like a usage habit of foreign languages. I reserved some english words used in engineering and program, like wfs request params, it's familiar to developers. As for `...` prefix, they follow the original english version.

**Comment by jansule** [comment]
Thanks for your feedback @initialdmg, that makes totally sense to me.

One further question before accepting your PR: Is it common to have six dots (……) instead of three (…)?

**Comment by initialdmg** [comment]
Yes,  `……` is the regular form of [ellipsis in Chinese](https://en.wikipedia.org/wiki/Ellipsis#In_Chinese). It's important to be rigorous. 👍 This PR needs more contributions to be better and professional.

**Comment by jansule** [comment]
Thanks again for your feedback.

This PR is a good starting point for zh-CN locales. So I will give a :+1: 

What do you think @KaiVolland 

@initialdmg is it ok, if we ping you in case we need additional translations in the future?

**Comment by initialdmg** [comment]
> @initialdmg is it ok, if we ping you in case we need additional translations in the future?

With pleasure!

**Comment by chrismayer** [comment]
> > @initialdmg is it ok, if we ping you in case we need additional translations in the future?
> 
> With pleasure!

Awesome, thank you!

**Pull request merged**
