### PR TITLE
feat: visibility field

### PR DESCRIPTION
**Pull request by miccoh1994**
## Description

Adds the VisibilityField to the Symbolizer Editor to toggle the visibility of each symbolizer.

 #1940 

Since the visibility property is available on each Symbolizer in geostyle I have placed it under the Kind select in the SymbolizerEditor.

## Do you introduce a breaking change?

- [ ] Yes
- [ ] No
- [x] I am unsure (no worries, we'll find out)

### CODE REVIEW

**Comment by KaiVolland** [comment]
Hey @miccoh1994 :wave: and thanks for the contribution. This looks great.

**Comment by KaiVolland** [comment]
@miccoh1994 Very nice. I checked it in the styleguide and just have one minor remark.

I think it would be better that the checkbox is only unchecked if the symbolizer is configured with `visibility: false`. If not configured at all or configured with `undefined` or `true` the checkbox should be checked. Could you adapt this?

**Comment by miccoh1994** [comment]
@KaiVolland thanks that makes sense, I did consider that but wasn't sure. I will work on it this weekend.

**Comment by KaiVolland** [comment]
@miccoh1994 will you be able to adapt this soon? Would be cool to have this feature in the next release.

**Comment by miccoh1994** [comment]
@KaiVolland adapted, not sure why the commit lint fails though.

**Review by KaiVolland — APPROVED** [review]

**Comment by KaiVolland** [comment]
Commit lint expects the commit message to start lowercase. I used squash commit to evade this.

**Pull request merged**
